"""
NOTE: This problem is a more challenging version of Problem 81.

The minimal path sum in the 5 by 5 matrix below, by starting in any cell in the left column and finishing in any cell in
the right column, and only moving up, down, and right, is indicated by (); the sum is equal to 994.

    131     673     (234)   (103)   (18)
    (201)   (96)    (342)   965     150
    630     803     746     422     111
    537     699     497     121     956
    805     732     524     37      331

Find the minimal path sum from the left column to the right column in matrix.txt (right click and
"Save Link/Target As..."), a 31K text file containing an 80 by 80 matrix.


---
Method:
- it can be observed that it would never be advantageous to go up/down on the leftmost column
    - otherwise, you could and should just start at the point you wanted to start
- thus, one could determine the cost (sum) to get from each row in column 1 to each row in column 2 by first moving to
the right, and then up/down the appropriate number of steps
    - if you do this for each number, and then take the minimum cost generated by each row, to recreate the column, one
    could collapse the entire matrix column by column
- if you collapse all the way across the matrix, you will be left with a single column at the end
    - simply taking the minimum of that column will provide the minimal path sum

--
Since it is apparently easier to deal with rows in numpy, we will modify the rules a little bit and deal with a
transposed matrix. With a transposed matrix, the starting position can be anywhere in the top row and we will finish
anywhere in the bottom row. Now, our available moves are only down, left, and right.

--
For each row, create a new row that will take in the cost to get to each column on the next row
e.g.
    1   4   4
    1   1   4
    4   1   1

Looking at the first row we get
    1   4   4
and the next row is
    1   1   4

To get to each element in the next row, one would get three different rows:
    ind0 == 1   [   2   3   7   ]
    ind1 == 4   [   6   5   9   ]
    ind2 == 4   [   10  9   8   ]
This was calculated by going down 1 row to the next element, and then adjacent as necessary to the correct column.
We can then take the minimum from each column and collapse the top two rows.
In this case, it turns out that ind0 row is all the minimum numbers.

So, now our matrix could be collapsed as follows:
    2   3   7
    4   1   1

The reason we can collapse the first row because those values represent the minimum cost function to get to that
location in the matrix.

Continuing in this matrix, we would get the following
    ind0 == 1   [   6   7   8   ]
    ind1 == 4   [   8   4   5   ]
    ind2 == 4   [   13  9   8   ]
Now taking the minimum from each column gives us
                [   6   4   5   ]

Given that this is our last row, we only need to find the minimum here to find the lowest cost function: 4

"""
import numpy as np

with open(file="p082_matrix.txt", mode="r") as f:
    data = np.loadtxt(f, delimiter=',', dtype=int)

# data = np.array((
#     [1, 1, 4],
#     [4, 1, 1],
#     [4, 4, 4]
# ))

# it seems that it is easier to iterate over rows, and so transpose to rows in order to make iterations easier
data = data.T

while data.shape[0] > 1:

    # pull the top_row and next_row for easy reference
    top_row = data[0]
    next_row = data[1]

    # go through each element and create a cost function to reach that location from any point within the row
    cost_list = []
    for i in range(len(next_row)):
        # initialize with the value from the row above at a specified index
        row_cost = [top_row[i]] * len(next_row)

        # then add the total values to get to each location in the next row
        for j in range(len(next_row)):
            if i == j:
                row_cost[j] += next_row[i]
            elif i < j:
                row_cost[j] += sum(next_row[i: j + 1])
            elif i > j:
                row_cost[j] += sum(next_row[j:i])

        # add this list to the cost_list, to be compared later
        cost_list.append(row_cost)

    # calculate the min_cost by finding the smallest element at each index in the cost_list
    min_cost = np.amin(cost_list, axis=0)

    # replace the next_row with the min_cost and delete the top row
    data[1] = min_cost
    data = np.delete(data, obj=0, axis=0)


print(data)
print(min(data[0]))