"""
NOTE: This problem is a more challenging version of Problem 81.

The minimal path sum in the 5 by 5 matrix below, by starting in any cell in the left column and finishing in any cell in
the right column, and only moving up, down, and right, is indicated by (); the sum is equal to 994.

    131     673     (234)   (103)   (18)
    (201)   (96)    (342)   965     150
    630     803     746     422     111
    537     699     497     121     956
    805     732     524     37      331

Find the minimal path sum from the left column to the right column in matrix.txt (right click and
"Save Link/Target As..."), a 31K text file containing an 80 by 80 matrix.

Method:
- it can be observed that it would never be advantageous to go up/down on the leftmost column
    - otherwise, you could and should just start at the point you wanted to start
- thus, one could determine the cost (sum) to get from each row in column 1 to each row in column 2 by first moving to
the right, and then up/down the appropriate number of steps
    - if you do this for each number, and then take the minimum cost generated by each row, to recreate the column, one
    could collapse the entire matrix column by column
- if you collapse all the way across the matrix, you will be left with a single column at the end
    - simply taking the minimum of that column will provide the minimal path sum

"""