/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.

--

Note that F(n) = F(n-1) + F(n-2)
*/

#include <iostream>

int main() {
    int limit {4000000};

    int f1 {1};
    int f2 {1};

    int sum = 0;
    while (f2 < limit) {
        // Calculate the next fibonacci number
        int f3 = f1 + f2;

        // Check if even and add to sum if yes
        if (f3 % 2 == 0) {
            sum += f3;
        }

        // Set the variables for the next loop
        f1 = f2;
        f2 = f3;
    }

    std::cout << "ans == " << sum << std::endl;

    return 0;
}